export const countryData = {
  "afghanistan": { name: "Afghanistan", iso: "af", code: "AFG", emoji: "🇦🇫" },
  "albania": { name: "Albania", iso: "al", code: "ALB", emoji: "🇦🇱" },
  "algeria": { name: "Algeria", iso: "dz", code: "DZA", emoji: "🇩🇿" },
  "andorra": { name: "Andorra", iso: "ad", code: "AND", emoji: "🇦🇩" },
  "angola": { name: "Angola", iso: "ao", code: "AGO", emoji: "🇦🇴" },
  "antigua and barbuda": { name: "Antigua and Barbuda", iso: "ag", code: "ATG", emoji: "🇦🇬" },
  "argentina": { name: "Argentina", iso: "ar", code: "ARG", emoji: "🇦🇷" },
  "armenia": { name: "Armenia", iso: "am", code: "ARM", emoji: "🇦🇲" },
  "australia": { name: "Australia", iso: "au", code: "AUS", emoji: "🇦🇺" },
  "austria": { name: "Austria", iso: "at", code: "AUT", emoji: "🇦🇹" },
  "azerbaijan": { name: "Azerbaijan", iso: "az", code: "AZE", emoji: "🇦🇿" },
  "bahamas": { name: "Bahamas", iso: "bs", code: "BHS", emoji: "🇧🇸" },
  "bahrain": { name: "Bahrain", iso: "bh", code: "BHR", emoji: "🇧🇭" },
  "bangladesh": { name: "Bangladesh", iso: "bd", code: "BGD", emoji: "🇧🇩" },
  "barbados": { name: "Barbados", iso: "bb", code: "BRB", emoji: "🇧🇧" },
  "belarus": { name: "Belarus", iso: "by", code: "BLR", emoji: "🇧🇾" },
  "belgium": { name: "Belgium", iso: "be", code: "BEL", emoji: "🇧🇪" },
  "belize": { name: "Belize", iso: "bz", code: "BLZ", emoji: "🇧🇿" },
  "benin": { name: "Benin", iso: "bj", code: "BEN", emoji: "🇧🇯" },
  "bhutan": { name: "Bhutan", iso: "bt", code: "BTN", emoji: "🇧🇹" },
  "bolivia": { name: "Bolivia", iso: "bo", code: "BOL", emoji: "🇧🇴" },
  "bosnia and herzegovina": { name: "Bosnia and Herzegovina", iso: "ba", code: "BIH", emoji: "🇧🇦" },
  "botswana": { name: "Botswana", iso: "bw", code: "BWA", emoji: "🇧🇼" },
  "brazil": { name: "Brazil", iso: "br", code: "BRA", emoji: "🇧🇷" },
  "brunei": { name: "Brunei", iso: "bn", code: "BRN", emoji: "🇧🇳" },
  "bulgaria": { name: "Bulgaria", iso: "bg", code: "BGR", emoji: "🇧🇬" },
  "burkina faso": { name: "Burkina Faso", iso: "bf", code: "BFA", emoji: "🇧🇫" },
  "burundi": { name: "Burundi", iso: "bi", code: "BDI", emoji: "🇧🇮" },
  "cabo verde": { name: "Cabo Verde", iso: "cv", code: "CPV", emoji: "🇨🇻" },
  "cambodia": { name: "Cambodia", iso: "kh", code: "KHM", emoji: "🇰🇭" },
  "cameroon": { name: "Cameroon", iso: "cm", code: "CMR", emoji: "🇨🇲" },
  "canada": { name: "Canada", iso: "ca", code: "CAN", emoji: "🇨🇦" },
  "central african republic": { name: "Central African Republic", iso: "cf", code: "CAF", emoji: "🇨🇫" },
  "chad": { name: "Chad", iso: "td", code: "TCD", emoji: "🇹🇩" },
  "chile": { name: "Chile", iso: "cl", code: "CHL", emoji: "🇨🇱" },
  "china": { name: "China", iso: "cn", code: "CHN", emoji: "🇨🇳" },
  "colombia": { name: "Colombia", iso: "co", code: "COL", emoji: "🇨🇴" },
  "comoros": { name: "Comoros", iso: "km", code: "COM", emoji: "🇰🇲" },
  "congo": { name: "Congo", iso: "cg", code: "COG", emoji: "🇨🇬" },
  "costa rica": { name: "Costa Rica", iso: "cr", code: "CRI", emoji: "🇨🇷" },
  "croatia": { name: "Croatia", iso: "hr", code: "HRV", emoji: "🇭🇷" },
  "cuba": { name: "Cuba", iso: "cu", code: "CUB", emoji: "🇨🇺" },
  "cyprus": { name: "Cyprus", iso: "cy", code: "CYP", emoji: "🇨🇾" },
  "czech republic": { name: "Czech Republic", iso: "cz", code: "CZE", emoji: "🇨🇿" },
  "denmark": { name: "Denmark", iso: "dk", code: "DNK", emoji: "🇩🇰" },
  "djibouti": { name: "Djibouti", iso: "dj", code: "DJI", emoji: "🇩🇯" },
  "dominica": { name: "Dominica", iso: "dm", code: "DMA", emoji: "🇩🇲" },
  "dominican republic": { name: "Dominican Republic", iso: "do", code: "DOM", emoji: "🇩🇴" },
  "ecuador": { name: "Ecuador", iso: "ec", code: "ECU", emoji: "🇪🇨" },
  "egypt": { name: "Egypt", iso: "eg", code: "EGY", emoji: "🇪🇬" },
  "el salvador": { name: "El Salvador", iso: "sv", code: "SLV", emoji: "🇸🇻" },
  "equatorial guinea": { name: "Equatorial Guinea", iso: "gq", code: "GNQ", emoji: "🇬🇶" },
  "eritrea": { name: "Eritrea", iso: "er", code: "ERI", emoji: "🇪🇷" },
  "estonia": { name: "Estonia", iso: "ee", code: "EST", emoji: "🇪🇪" },
  "eswatini": { name: "Eswatini", iso: "sz", code: "SWZ", emoji: "🇸🇿" },
  "ethiopia": { name: "Ethiopia", iso: "et", code: "ETH", emoji: "🇪🇹" },
  "fiji": { name: "Fiji", iso: "fj", code: "FJI", emoji: "🇫🇯" },
  "finland": { name: "Finland", iso: "fi", code: "FIN", emoji: "🇫🇮" },
  "france": { name: "France", iso: "fr", code: "FRA", emoji: "🇫🇷" },
  "gabon": { name: "Gabon", iso: "ga", code: "GAB", emoji: "🇬🇦" },
  "gambia": { name: "Gambia", iso: "gm", code: "GMB", emoji: "🇬🇲" },
  "georgia": { name: "Georgia", iso: "ge", code: "GEO", emoji: "🇬🇪" },
  "germany": { name: "Germany", iso: "de", code: "DEU", emoji: "🇩🇪" },
  "ghana": { name: "Ghana", iso: "gh", code: "GHA", emoji: "🇬🇭" },
  "greece": { name: "Greece", iso: "gr", code: "GRC", emoji: "🇬🇷" },
  "grenada": { name: "Grenada", iso: "gd", code: "GRD", emoji: "🇬🇩" },
  "guatemala": { name: "Guatemala", iso: "gt", code: "GTM", emoji: "🇬🇹" },
  "guinea": { name: "Guinea", iso: "gn", code: "GIN", emoji: "🇬🇳" },
  "guinea-bissau": { name: "Guinea-Bissau", iso: "gw", code: "GNB", emoji: "🇬🇼" },
  "guyana": { name: "Guyana", iso: "gy", code: "GUY", emoji: "🇬🇾" },
  "haiti": { name: "Haiti", iso: "ht", code: "HTI", emoji: "🇭🇹" },
  "honduras": { name: "Honduras", iso: "hn", code: "HND", emoji: "🇭🇳" },
  "hungary": { name: "Hungary", iso: "hu", code: "HUN", emoji: "🇭🇺" },
  "iceland": { name: "Iceland", iso: "is", code: "ISL", emoji: "🇮🇸" },
  "india": { name: "India", iso: "in", code: "IND", emoji: "🇮🇳" },
  "indonesia": { name: "Indonesia", iso: "id", code: "IDN", emoji: "🇮🇩" },
  "iran": { name: "Iran", iso: "ir", code: "IRN", emoji: "🇮🇷" },
  "iraq": { name: "Iraq", iso: "iq", code: "IRQ", emoji: "🇮🇶" },
  "ireland": { name: "Ireland", iso: "ie", code: "IRL", emoji: "🇮🇪" },
  "israel": { name: "Israel", iso: "il", code: "ISR", emoji: "🇮🇱" },
  "italy": { name: "Italy", iso: "it", code: "ITA", emoji: "🇮🇹" },
  "jamaica": { name: "Jamaica", iso: "jm", code: "JAM", emoji: "🇯🇲" },
  "japan": { name: "Japan", iso: "jp", code: "JPN", emoji: "🇯🇵" },
  "jordan": { name: "Jordan", iso: "jo", code: "JOR", emoji: "🇯🇴" },
  "kazakhstan": { name: "Kazakhstan", iso: "kz", code: "KAZ", emoji: "🇰🇿" },
  "kenya": { name: "Kenya", iso: "ke", code: "KEN", emoji: "🇰🇪" },
  "kiribati": { name: "Kiribati", iso: "ki", code: "KIR", emoji: "🇰🇮" },
  "kuwait": { name: "Kuwait", iso: "kw", code: "KWT", emoji: "🇰🇼" },
  "kyrgyzstan": { name: "Kyrgyzstan", iso: "kg", code: "KGZ", emoji: "🇰🇬" },
  "laos": { name: "Laos", iso: "la", code: "LAO", emoji: "🇱🇦" },
  "latvia": { name: "Latvia", iso: "lv", code: "LVA", emoji: "🇱🇻" },
  "lebanon": { name: "Lebanon", iso: "lb", code: "LBN", emoji: "🇱🇧" },
  "lesotho": { name: "Lesotho", iso: "ls", code: "LSO", emoji: "🇱🇸" },
  "liberia": { name: "Liberia", iso: "lr", code: "LBR", emoji: "🇱🇷" },
  "libya": { name: "Libya", iso: "ly", code: "LBY", emoji: "🇱🇾" },
  "liechtenstein": { name: "Liechtenstein", iso: "li", code: "LIE", emoji: "🇱🇮" },
  "lithuania": { name: "Lithuania", iso: "lt", code: "LTU", emoji: "🇱🇹" },
  "luxembourg": { name: "Luxembourg", iso: "lu", code: "LUX", emoji: "🇱🇺" },
  "madagascar": { name: "Madagascar", iso: "mg", code: "MDG", emoji: "🇲🇬" },
  "malawi": { name: "Malawi", iso: "mw", code: "MWI", emoji: "🇲🇼" },
  "malaysia": { name: "Malaysia", iso: "my", code: "MYS", emoji: "🇲🇾" },
  "maldives": { name: "Maldives", iso: "mv", code: "MDV", emoji: "🇲🇻" },
  "mali": { name: "Mali", iso: "ml", code: "MLI", emoji: "🇲🇱" },
  "malta": { name: "Malta", iso: "mt", code: "MLT", emoji: "🇲🇹" },
  "marshall islands": { name: "Marshall Islands", iso: "mh", code: "MHL", emoji: "🇲🇭" },
  "mauritania": { name: "Mauritania", iso: "mr", code: "MRT", emoji: "🇲🇷" },
  "mauritius": { name: "Mauritius", iso: "mu", code: "MUS", emoji: "🇲🇺" },
  "mexico": { name: "Mexico", iso: "mx", code: "MEX", emoji: "🇲🇽" },
  "micronesia": { name: "Micronesia", iso: "fm", code: "FSM", emoji: "🇫🇲" },
  "moldova": { name: "Moldova", iso: "md", code: "MDA", emoji: "🇲🇩" },
  "monaco": { name: "Monaco", iso: "mc", code: "MCO", emoji: "🇲🇨" },
  "mongolia": { name: "Mongolia", iso: "mn", code: "MNG", emoji: "🇲🇳" },
  "montenegro": { name: "Montenegro", iso: "me", code: "MNE", emoji: "🇲🇪" },
  "morocco": { name: "Morocco", iso: "ma", code: "MAR", emoji: "🇲🇦" },
  "mozambique": { name: "Mozambique", iso: "mz", code: "MOZ", emoji: "🇲🇿" },
  "myanmar": { name: "Myanmar", iso: "mm", code: "MMR", emoji: "🇲🇲" },
  "namibia": { name: "Namibia", iso: "na", code: "NAM", emoji: "🇳🇦" },
  "nauru": { name: "Nauru", iso: "nr", code: "NRU", emoji: "🇳🇷" },
  "nepal": { name: "Nepal", iso: "np", code: "NPL", emoji: "🇳🇵" },
  "netherlands": { name: "Netherlands", iso: "nl", code: "NLD", emoji: "🇳🇱" },
  "new zealand": { name: "New Zealand", iso: "nz", code: "NZL", emoji: "🇳🇿" },
  "nicaragua": { name: "Nicaragua", iso: "ni", code: "NIC", emoji: "🇳🇮" },
  "niger": { name: "Niger", iso: "ne", code: "NER", emoji: "🇳🇪" },
  "nigeria": { name: "Nigeria", iso: "ng", code: "NGA", emoji: "🇳🇬" },
  "north korea": { name: "North Korea", iso: "kp", code: "PRK", emoji: "🇰🇵" },
  "north macedonia": { name: "North Macedonia", iso: "mk", code: "MKD", emoji: "🇲🇰" },
  "norway": { name: "Norway", iso: "no", code: "NOR", emoji: "🇳🇴" },
  "oman": { name: "Oman", iso: "om", code: "OMN", emoji: "🇴🇲" },
  "pakistan": { name: "Pakistan", iso: "pk", code: "PAK", emoji: "🇵🇰" },
  "palau": { name: "Palau", iso: "pw", code: "PLW", emoji: "🇵🇼" },
  "palestine": { name: "Palestine", iso: "ps", code: "PSE", emoji: "🇵🇸" },
  "panama": { name: "Panama", iso: "pa", code: "PAN", emoji: "🇵🇦" },
  "papua new guinea": { name: "Papua New Guinea", iso: "pg", code: "PNG", emoji: "🇵🇬" },
  "paraguay": { name: "Paraguay", iso: "py", code: "PRY", emoji: "🇵🇾" },
  "peru": { name: "Peru", iso: "pe", code: "PER", emoji: "🇵🇪" },
  "philippines": { name: "Philippines", iso: "ph", code: "PHL", emoji: "🇵🇭" },
  "poland": { name: "Poland", iso: "pl", code: "POL", emoji: "🇵🇱" },
  "portugal": { name: "Portugal", iso: "pt", code: "PRT", emoji: "🇵🇹" },
  "qatar": { name: "Qatar", iso: "qa", code: "QAT", emoji: "🇶🇦" },
  "romania": { name: "Romania", iso: "ro", code: "ROU", emoji: "🇷🇴" },
  "russia": { name: "Russia", iso: "ru", code: "RUS", emoji: "🇷🇺" },
  "rwanda": { name: "Rwanda", iso: "rw", code: "RWA", emoji: "🇷🇼" },
  "saint kitts and nevis": { name: "Saint Kitts and Nevis", iso: "kn", code: "KNA", emoji: "🇰🇳" },
  "saint lucia": { name: "Saint Lucia", iso: "lc", code: "LCA", emoji: "🇱🇨" },
  "saint vincent and the grenadines": { name: "Saint Vincent and the Grenadines", iso: "vc", code: "VCT", emoji: "🇻🇨" },
  "samoa": { name: "Samoa", iso: "ws", code: "WSM", emoji: "🇼🇸" },
  "san marino": { name: "San Marino", iso: "sm", code: "SMR", emoji: "🇸🇲" },
  "sao tome and principe": { name: "Sao Tome and Principe", iso: "st", code: "STP", emoji: "🇸🇹" },
  "saudi arabia": { name: "Saudi Arabia", iso: "sa", code: "SAU", emoji: "🇸🇦" },
  "senegal": { name: "Senegal", iso: "sn", code: "SEN", emoji: "🇸🇳" },
  "serbia": { name: "Serbia", iso: "rs", code: "SRB", emoji: "🇷🇸" },
  "seychelles": { name: "Seychelles", iso: "sc", code: "SYC", emoji: "🇸🇨" },
  "sierra leone": { name: "Sierra Leone", iso: "sl", code: "SLE", emoji: "🇸🇱" },
  "singapore": { name: "Singapore", iso: "sg", code: "SGP", emoji: "🇸🇬" },
  "slovakia": { name: "Slovakia", iso: "sk", code: "SVK", emoji: "🇸🇰" },
  "slovenia": { name: "Slovenia", iso: "si", code: "SVN", emoji: "🇸🇮" },
  "solomon islands": { name: "Solomon Islands", iso: "sb", code: "SLB", emoji: "🇸🇧" },
  "somalia": { name: "Somalia", iso: "so", code: "SOM", emoji: "🇸🇴" },
  "south africa": { name: "South Africa", iso: "za", code: "ZAF", emoji: "🇿🇦" },
  "south korea": { name: "South Korea", iso: "kr", code: "KOR", emoji: "🇰🇷" },
  "south sudan": { name: "South Sudan", iso: "ss", code: "SSD", emoji: "🇸🇸" },
  "spain": { name: "Spain", iso: "es", code: "ESP", emoji: "🇪🇸" },
  "sri lanka": { name: "Sri Lanka", iso: "lk", code: "LKA", emoji: "🇱🇰" },
  "sudan": { name: "Sudan", iso: "sd", code: "SDN", emoji: "🇸🇩" },
  "suriname": { name: "Suriname", iso: "sr", code: "SUR", emoji: "🇸🇷" },
  "sweden": { name: "Sweden", iso: "se", code: "SWE", emoji: "🇸🇪" },
  "switzerland": { name: "Switzerland", iso: "ch", code: "CHE", emoji: "🇨🇭" },
  "syria": { name: "Syria", iso: "sy", code: "SYR", emoji: "🇸🇾" },
  "taiwan": { name: "Taiwan", iso: "tw", code: "TWN", emoji: "🇹🇼" },
  "tajikistan": { name: "Tajikistan", iso: "tj", code: "TJK", emoji: "🇹🇯" },
  "tanzania": { name: "Tanzania", iso: "tz", code: "TZA", emoji: "🇹🇿" },
  "thailand": { name: "Thailand", iso: "th", code: "THA", emoji: "🇹🇭" },
  "timor-leste": { name: "Timor-Leste", iso: "tl", code: "TLS", emoji: "🇹🇱" },
  "togo": { name: "Togo", iso: "tg", code: "TGO", emoji: "🇹🇬" },
  "tonga": { name: "Tonga", iso: "to", code: "TON", emoji: "🇹🇴" },
  "trinidad and tobago": { name: "Trinidad and Tobago", iso: "tt", code: "TTO", emoji: "🇹🇹" },
  "tunisia": { name: "Tunisia", iso: "tn", code: "TUN", emoji: "🇹🇳" },
  "turkey": { name: "Turkey", iso: "tr", code: "TUR", emoji: "🇹🇷" },
  "turkmenistan": { name: "Turkmenistan", iso: "tm", code: "TKM", emoji: "🇹🇲" },
  "tuvalu": { name: "Tuvalu", iso: "tv", code: "TUV", emoji: "🇹🇻" },
  "uganda": { name: "Uganda", iso: "ug", code: "UGA", emoji: "🇺🇬" },
  "ukraine": { name: "Ukraine", iso: "ua", code: "UKR", emoji: "🇺🇦" },
  "united arab emirates": { name: "United Arab Emirates", iso: "ae", code: "ARE", emoji: "🇦🇪" },
  "uae": { name: "UAE", iso: "ae", code: "ARE", emoji: "🇦🇪" },
  "united kingdom": { name: "United Kingdom", iso: "gb", code: "GBR", emoji: "🇬🇧" },
  "uk": { name: "UK", iso: "gb", code: "GBR", emoji: "🇬🇧" },
  "united states": { name: "United States", iso: "us", code: "USA", emoji: "🇺🇸" },
  "usa": { name: "USA", iso: "us", code: "USA", emoji: "🇺🇸" },
  "uruguay": { name: "Uruguay", iso: "uy", code: "URY", emoji: "🇺🇾" },
  "uzbekistan": { name: "Uzbekistan", iso: "uz", code: "UZB", emoji: "🇺🇿" },
  "vanuatu": { name: "Vanuatu", iso: "vu", code: "VUT", emoji: "🇻🇺" },
  "vatican city": { name: "Vatican City", iso: "va", code: "VAT", emoji: "🇻🇦" },
  "venezuela": { name: "Venezuela", iso: "ve", code: "VEN", emoji: "🇻🇪" },
  "vietnam": { name: "Vietnam", iso: "vn", code: "VNM", emoji: "🇻🇳" },
  "yemen": { name: "Yemen", iso: "ye", code: "YEM", emoji: "🇾🇪" },
  "zambia": { name: "Zambia", iso: "zm", code: "ZMB", emoji: "🇿🇲" },
  "zimbabwe": { name: "Zimbabwe", iso: "zw", code: "ZWE", emoji: "🇿🇼" }
};

export const popularCities = [
  { city: "Tokyo", country: "Japan" },
  { city: "Kyoto", country: "Japan" },
  { city: "Osaka", country: "Japan" },
  { city: "Paris", country: "France" },
  { city: "Nice", country: "France" },
  { city: "Rome", country: "Italy" },
  { city: "Milan", country: "Italy" },
  { city: "Venice", country: "Italy" },
  { city: "Florence", country: "Italy" },
  { city: "New York", country: "United States" },
  { city: "Los Angeles", country: "United States" },
  { city: "San Francisco", country: "United States" },
  { city: "Chicago", country: "United States" },
  { city: "Miami", country: "United States" },
  { city: "London", country: "United Kingdom" },
  { city: "Edinburgh", country: "United Kingdom" },
  { city: "Manchester", country: "United Kingdom" },
  { city: "Sydney", country: "Australia" },
  { city: "Melbourne", country: "Australia" },
  { city: "Brisbane", country: "Australia" },
  { city: "Mumbai", country: "India" },
  { city: "Delhi", country: "India" },
  { city: "Bangalore", country: "India" },
  { city: "Goa", country: "India" },
  { city: "Dubai", country: "United Arab Emirates" },
  { city: "Abu Dhabi", country: "United Arab Emirates" },
  { city: "Singapore", country: "Singapore" },
  { city: "Toronto", country: "Canada" },
  { city: "Vancouver", country: "Canada" },
  { city: "Montreal", country: "Canada" },
  { city: "Bangkok", country: "Thailand" },
  { city: "Phuket", country: "Thailand" },
  { city: "Chiang Mai", country: "Thailand" },
  { city: "Bali", country: "Indonesia" },
  { city: "Jakarta", country: "Indonesia" },
  { city: "Seoul", country: "South Korea" },
  { city: "Busan", country: "South Korea" },
  { city: "Beijing", country: "China" },
  { city: "Shanghai", country: "China" },
  { city: "Hong Kong", country: "China" },
  { city: "Cairo", country: "Egypt" },
  { city: "Istanbul", country: "Turkey" },
  { city: "Antalya", country: "Turkey" },
  { city: "Cape Town", country: "South Africa" },
  { city: "Johannesburg", country: "South Africa" },
  { city: "Rio de Janeiro", country: "Brazil" },
  { city: "Sao Paulo", country: "Brazil" },
  { city: "Buenos Aires", country: "Argentina" },
  { city: "Santiago", country: "Chile" },
  { city: "Mexico City", country: "Mexico" },
  { city: "Cancun", country: "Mexico" },
  { city: "Reykjavik", country: "Iceland" },
  { city: "Athens", country: "Greece" },
  { city: "Santorini", country: "Greece" },
  { city: "Madrid", country: "Spain" },
  { city: "Barcelona", country: "Spain" },
  { city: "Berlin", country: "Germany" },
  { city: "Munich", country: "Germany" },
  { city: "Frankfurt", country: "Germany" },
  { city: "Zurich", country: "Switzerland" },
  { city: "Geneva", country: "Switzerland" },
  { city: "Amsterdam", country: "Netherlands" },
  { city: "Brussels", country: "Belgium" },
  { city: "Vienna", country: "Austria" },
  { city: "Copenhagen", country: "Denmark" },
  { city: "Oslo", country: "Norway" },
  { city: "Stockholm", country: "Sweden" },
  { city: "Helsinki", country: "Finland" },
  { city: "Lisbon", country: "Portugal" },
  { city: "Porto", country: "Portugal" },
  { city: "Dublin", country: "Ireland" },
  { city: "Prague", country: "Czech Republic" },
  { city: "Budapest", country: "Hungary" },
  { city: "Warsaw", country: "Poland" },
  { city: "Krakow", country: "Poland" },
  { city: "Auckland", country: "New Zealand" },
  { city: "Queenstown", country: "New Zealand" },
  { city: "Kuala Lumpur", country: "Malaysia" },
  { city: "Manila", country: "Philippines" },
  { city: "Ho Chi Minh City", country: "Vietnam" },
  { city: "Hanoi", country: "Vietnam" },
  { city: "Lima", country: "Peru" },
  { city: "Bogota", country: "Colombia" },
  { city: "Nairobi", country: "Kenya" },
  { city: "Marrakech", country: "Morocco" },
  { city: "Casablanca", country: "Morocco" }
];
